server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: com.wdw.gateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: Http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1    #路由的ID，没有具体规范，但是要唯一，最好和服务匹配
#          uri: http://localhost:8001   #匹配后路由的地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址，注册中心的服务名称
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
            - Cookie=username,wdw   #表示需要带有cookie 值是username=wdw
            - Header=X-request-Id,\d  #表示需要请求头中有X-request-Id的属性，值为整数
        - id: payment_routh2    #路由的ID，没有具体规范，但是要唯一，最好和服务匹配
#          uri: http://localhost:8001   #匹配后路由的地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址，注册中心的服务名称
          predicates:
              - Path=/getPort/**   #断言，路径相匹配的进行路由
              - Cookie=username,wdw #表示需要带有cookie 值是username=wdw
              - Header=X-request-Id,\d  #表示需要请求头中有X-request-Id的属性，值为整数，只能有一个
              - Method=GET  #请求方法
              - Query=username,\d+ #要带有参数，并且值为整数
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由，由服务名进行路由
