server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com #注册中心eureka服务器的实例名称
  client:
    register-with-eureka: false #false表示不向erueka服务注册自己本身
    fetch-registry: false #false表示自己就是注册中心，职责就是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/erueka/,http://eureka7002.com:7002/erueka/
